###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: webservice-laravel-5-5-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=db_crud
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "8002:3306"

    webserver:
      image: nginx:alpine
      container_name: webservice-laravel-5-5-webserver
      working_dir: /application
      volumes:
          - ./api:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: webservice-laravel-5-5-php-fpm
      working_dir: /application
      volumes:
        - ./api:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

